# Generated by Django 5.1.1 on 2024-09-15 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Urun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=255)),
                ('aciklama', models.TextField(blank=True, null=True)),
                ('fiyat', models.DecimalField(decimal_places=2, max_digits=10)),
                ('resim', models.ImageField(blank=True, null=True, upload_to='urunler/')),
                ('kategori1', models.CharField(blank=True, max_length=255, null=True)),
                ('kategori2', models.CharField(blank=True, max_length=255, null=True)),
                ('urun_tipi', models.CharField(choices=[('FIZIKSEL', 'Fiziksel'), ('Dijital', 'Dijital')], default='FIZIKSEL', max_length=50)),
            ],
        ),
    ]
